### ISSUE TITLE
How to keep the cause of an error

### ISSUE THREAD

**Issue by puko313** [puko313/NFT-marketplace-v3#1]
I have a background of Java developer and I'm quite new to JavaScript/TypeScript.

Is there a standard way to manage and keep the cause of an Error in JavaScript/TypeScript?

My purpose is to get a complete stacktrace when I wrap an Error into another ; a little bit as with Java Exception stacktrace:

```
Message of exception 1
...
Caused by: Message of exception 2
...
Caused by: Message of the root exception
```

**Comment by SuperDev313** [comment]
JavaScript and TypeScript have mechanisms to manage and preserve the cause of an error when wrapping one error into another, similar to Java's exception chaining. This can be achieved by leveraging the cause property introduced in ECMAScript 2022.
```

try {
    // Root operation that throws an error
    throw new Error("Root exception");
} catch (rootError) {
    try {
        // Another operation that throws an error, caused by rootError
        throw new Error("Exception 2", { cause: rootError });
    } catch (secondError) {
        // Final wrapping error, caused by secondError
        throw new Error("Exception 1", { cause: secondError });
    }
}
```

**Comment by SuperDev313** [comment]
> JavaScript and TypeScript have mechanisms to manage and preserve the cause of an error when wrapping one error into another, similar to Java's exception chaining. This can be achieved by leveraging the cause property introduced in ECMAScript 2022.
> 
> ```
> 
> try {
>     // Root operation that throws an error
>     throw new Error("Root exception");
> } catch (rootError) {
>     try {
>         // Another operation that throws an error, caused by rootError
>         throw new Error("Exception 2", { cause: rootError });
>     } catch (secondError) {
>         // Final wrapping error, caused by secondError
>         throw new Error("Exception 1", { cause: secondError });
>     }
> }
> ```



> JavaScript and TypeScript have mechanisms to manage and preserve the cause of an error when wrapping one error into another, similar to Java's exception chaining. This can be achieved by leveraging the cause property introduced in ECMAScript 2022.
> 
> ```
> 
> try {
>     // Root operation that throws an error
>     throw new Error("Root exception");
> } catch (rootError) {
>     try {
>         // Another operation that throws an error, caused by rootError
>         throw new Error("Exception 2", { cause: rootError });
>     } catch (secondError) {
>         // Final wrapping error, caused by secondError
>         throw new Error("Exception 1", { cause: secondError });
>     }
> }
> ```
Thank you
